package com.sudsmobile.shared.theme

import androidx.compose.ui.graphics.Color

/**
 * Customer-facing brand colours. These are intentionally separate from the
 * Material colour schemes below so legacy and admin surfaces can migrate
 * independently.
 */
object SudsColors {
    val ink = Color(0xFF07151F)
    val navy = Color(0xFF102C3C)
    val navyElevated = Color(0xFF183D50)
    val brandBackgroundTop = Color(0xFF020C16)
    val brandBackgroundMiddle = Color(0xFF061827)
    val brandBackgroundBottom = Color(0xFF03111F)
    val cyan = Color(0xFF54D8E8)
    val cyanMuted = Color(0xFF9AE8EF)
    val cyanDeep = Color(0xFF2DBBE6)
    val cyanBright = Color(0xFF69E5F1)
    val actionGradient = listOf(cyanDeep, cyan, cyanBright)
    val champagne = Color(0xFFF4D57A)
    val glass = Color(0x1FFFFFFF)
    val glassStrong = Color(0x2EFFFFFF)
    val glassBorder = Color(0x38FFFFFF)
    val onBrand = Color(0xFFF7FBFD)
    val onBrandMuted = Color(0xC4F7FBFD)
    val onAction = Color(0xFF05232A)
    val success = Color(0xFF75D6A7)
    val warning = Color(0xFFFFC56E)
    val error = Color(0xFFFF9B9B)
    val scrim = Color(0x99030D13)
    val transparent = Color(0x00000000)
}

internal val PrimaryLight = Color(0xFF36618E)
internal val OnPrimaryLight = Color(0xFFFFFFFF)
internal val PrimaryContainerLight = Color(0xFFD2E4FF)
internal val OnPrimaryContainerLight = Color(0xFF1A4975)
internal val SecondaryLight = Color(0xFF33618D)
internal val OnSecondaryLight = Color(0xFFFFFFFF)
internal val SecondaryContainerLight = Color(0xFFD0E4FF)
internal val OnSecondaryContainerLight = Color(0xFF154974)
internal val TertiaryLight = Color(0xFF725C0C)
internal val OnTertiaryLight = Color(0xFFFFFFFF)
internal val TertiaryContainerLight = Color(0xFFFFE088)
internal val OnTertiaryContainerLight = Color(0xFF574500)
internal val ErrorLight = Color(0xFF8F4A4D)
internal val OnErrorLight = Color(0xFFFFFFFF)
internal val ErrorContainerLight = Color(0xFFFFDADA)
internal val OnErrorContainerLight = Color(0xFF733336)
internal val BackgroundLight = Color(0xFFF8F9FF)
internal val OnBackgroundLight = Color(0xFF191C20)
internal val SurfaceLight = Color(0xFFF6FAFE)
internal val OnSurfaceLight = Color(0xFF181C1F)
internal val SurfaceVariantLight = Color(0xFFDEE3EB)
internal val OnSurfaceVariantLight = Color(0xFF42474E)
internal val OutlineLight = Color(0xFF72777F)
internal val OutlineVariantLight = Color(0xFFC2C7CF)
internal val ScrimLight = Color(0xFF000000)
internal val InverseSurfaceLight = Color(0xFF2C3134)
internal val InverseOnSurfaceLight = Color(0xFFEDF1F5)
internal val InversePrimaryLight = Color(0xFFA1CAFD)
internal val SurfaceDimLight = Color(0xFFD7DADF)
internal val SurfaceBrightLight = Color(0xFFF6FAFE)
internal val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val SurfaceContainerLowLight = Color(0xFFF0F4F8)
internal val SurfaceContainerLight = Color(0xFFEAEEF3)
internal val SurfaceContainerHighLight = Color(0xFFE5E8ED)
internal val SurfaceContainerHighestLight = Color(0xFFDFE3E7)

internal val PrimaryDark = Color(0xFFA1CAFD)
internal val OnPrimaryDark = Color(0xFF003259)
internal val PrimaryContainerDark = Color(0xFF1A4975)
internal val OnPrimaryContainerDark = Color(0xFFD2E4FF)
internal val SecondaryDark = Color(0xFF9ECAFC)
internal val OnSecondaryDark = Color(0xFF003256)
internal val SecondaryContainerDark = Color(0xFF154974)
internal val OnSecondaryContainerDark = Color(0xFFD0E4FF)
internal val TertiaryDark = Color(0xFFE2C46D)
internal val OnTertiaryDark = Color(0xFF3C2F00)
internal val TertiaryContainerDark = Color(0xFF574500)
internal val OnTertiaryContainerDark = Color(0xFFFFE088)
internal val ErrorDark = Color(0xFFFFB3B4)
internal val OnErrorDark = Color(0xFF561D21)
internal val ErrorContainerDark = Color(0xFF733336)
internal val OnErrorContainerDark = Color(0xFFFFDADA)
internal val BackgroundDark = Color(0xFF111418)
internal val OnBackgroundDark = Color(0xFFE1E2E8)
internal val SurfaceDark = Color(0xFF0F1417)
internal val OnSurfaceDark = Color(0xFFDFE3E7)
internal val SurfaceVariantDark = Color(0xFF42474E)
internal val OnSurfaceVariantDark = Color(0xFFC2C7CF)
internal val OutlineDark = Color(0xFF8C9198)
internal val OutlineVariantDark = Color(0xFF42474E)
internal val ScrimDark = Color(0xFF000000)
internal val InverseSurfaceDark = Color(0xFFDFE3E7)
internal val InverseOnSurfaceDark = Color(0xFF2C3134)
internal val InversePrimaryDark = Color(0xFF36618E)
internal val SurfaceDimDark = Color(0xFF0F1417)
internal val SurfaceBrightDark = Color(0xFF353A3D)
internal val SurfaceContainerLowestDark = Color(0xFF0A0F12)
internal val SurfaceContainerLowDark = Color(0xFF181C1F)
internal val SurfaceContainerDark = Color(0xFF1C2023)
internal val SurfaceContainerHighDark = Color(0xFF262B2E)
internal val SurfaceContainerHighestDark = Color(0xFF313539)
